# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cfd02383-7942-4a9a-bf9a-640cf265a0d4";
    fsType = "btrfs";
    options = [ "subvol=@" "compress=zstd:3" "discard=async" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/cfd02383-7942-4a9a-bf9a-640cf265a0d4";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd:3" "discard=async" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3CE4-EE3B";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/nvme" =
    { device = "/dev/disk/by-uuid/1a0038b9-d7d6-439c-9e0b-f1ffe7ab2fad";
      fsType = "ext4";
    };

  fileSystems."/mnt/ssd1" =
    { device = "/dev/disk/by-uuid/ec192eca-ab66-44a3-b47c-30a63003ca21";
      fsType = "ext4";
    };

  fileSystems."/mnt/ssd2" =
    { device = "/dev/disk/by-uuid/704b3630-788d-4704-bb66-bb49087c8316";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
